project_id = "vevuduwmzoucjaqqdfzw"

[functions.sync-lotofacil]
verify_jwt = false

[functions.identificar-conta]
verify_jwt = false

[functions.generate-guide-post]
verify_jwt = false

[functions.seed-guides]
verify_jwt = false
