// Lista expandida de domínios de email descartáveis/temporários
// Fonte base: github.com/disposable-email-domains/disposable-email-domains
// Mantida em ordem alfabética para facilitar manutenção
export const DISPOSABLE_DOMAINS = new Set<string>([
  "0-mail.com", "0clickemail.com", "0wnd.net", "0wnd.org", "10minutemail.com",
  "10minutemail.net", "10minutesmail.com", "12minutemail.com", "1secmail.com",
  "1secmail.net", "1secmail.org", "20minutemail.com", "2prong.com",
  "30minutemail.com", "33mail.com", "3d-painting.com", "4warding.com",
  "5ymail.com", "60minutemail.com", "675hosting.com", "75hosting.com",
  "7tags.com", "9ox.net", "afrobacon.com", "ag.us.to", "amilegit.com",
  "anonbox.net", "anonymbox.com", "antichef.com", "antichef.net",
  "antispam.de", "armyspy.com", "azmeil.tk", "baxomale.ht.cx",
  "beefmilk.com", "bigstring.com", "binkmail.com", "bio-muesli.net",
  "bobmail.info", "bofthew.com", "boximail.com", "broadbandninja.com",
  "bsnow.net", "bspamfree.org", "bugmenot.com", "bumpymail.com",
  "burnermail.io", "burstmail.info", "buymoreplays.com", "byom.de",
  "centermail.com", "centermail.net", "chammy.info", "chogmail.com",
  "choicemail1.com", "clipmail.eu", "cool.fr.nf", "courriel.fr.nf",
  "courrieltemporaire.com", "cubiclink.com", "curryworld.de", "cust.in",
  "cuvox.de", "dacoolest.com", "dandikmail.com", "dayrep.com",
  "deadaddress.com", "deadspam.com", "delikkt.de", "despam.it",
  "despammed.com", "devnullmail.com", "dfgh.net", "digitalsanctuary.com",
  "dingbone.com", "discard.email", "discardmail.com", "discardmail.de",
  "disposableaddress.com", "disposableemailaddresses.com", "disposableinbox.com",
  "dispose.it", "disposeamail.com", "disposemail.com", "dispostable.com",
  "dodgeit.com", "dodgit.com", "donemail.ru", "dontreg.com", "dontsendmespam.de",
  "drdrb.net", "dump-email.info", "dumpandjunk.com", "dumpyemail.com",
  "e4ward.com", "easytrashmail.com", "einrot.com", "eintagsmail.de",
  "email60.com", "emaildienst.de", "emailgo.de", "emailias.com",
  "emailinfive.com", "emaillime.com", "emailmiser.com", "emailsensei.com",
  "emailtemporanea.net", "emailthe.net", "emailtmp.com", "emailwarden.com",
  "emailx.at.hm", "emailxfer.com", "emeil.in", "emeil.ir", "emz.net",
  "evopo.com", "explodemail.com", "express.net.ua", "eyepaste.com",
  "fakeinbox.com", "fakemailz.com", "fastacura.com", "fastchevy.com",
  "fastmailbox.net", "fasttrackemail.com", "fightallspam.com",
  "filzmail.com", "fizmail.com", "fleckens.hu", "fr33mail.info",
  "frapmail.com", "friendlymail.co.uk", "fux0ringduh.com", "garliclife.com",
  "get1mail.com", "get2mail.fr", "getairmail.com", "getmails.eu",
  "getnada.com", "getonemail.com", "ghosttexter.de", "girlsundertheinfluence.com",
  "gishpuppy.com", "gmial.com", "gnail.com", "goemailgo.com", "gowikibooks.com",
  "gsrv.co.uk", "guerillamail.biz", "guerillamail.com", "guerillamail.de",
  "guerillamail.info", "guerillamail.net", "guerillamail.org", "guerrillamail.biz",
  "guerrillamail.com", "guerrillamail.de", "guerrillamail.info", "guerrillamail.net",
  "guerrillamail.org", "guerrillamailblock.com", "h.mintemail.com",
  "haltospam.com", "harakirimail.com", "hatespam.org", "hidzz.com",
  "hmamail.com", "hochsitze.com", "hotmial.com", "hotmai.com", "hulapla.de",
  "ieatspam.eu", "ieatspam.info", "ihateyoualot.info", "iheartspam.org",
  "imails.info", "inbax.tk", "inbox.si", "inboxalias.com", "inboxbear.com",
  "inboxclean.com", "inboxclean.org", "incognitomail.com", "incognitomail.net",
  "incognitomail.org", "insorg-mail.info", "instant-mail.de", "ip6.li",
  "irish2me.com", "iwi.net", "jetable.com", "jetable.fr.nf", "jetable.net",
  "jetable.org", "jnxjn.com", "jourrapide.com", "junkmail.ga", "junkmail.gq",
  "kasmail.com", "kaspop.com", "keepmymail.com", "killmail.com", "killmail.net",
  "klassmaster.com", "klzlk.com", "koszmail.pl", "kurzepost.de", "lawlita.com",
  "letthemeatspam.com", "lhsdv.com", "lifebyfood.com", "link2mail.net",
  "litedrop.com", "lol.ovpn.to", "lookugly.com", "lortemail.dk", "lr78.com",
  "lroid.com", "lukop.dk", "m4ilweb.info", "maboard.com", "mail-filter.com",
  "mail-temporaire.fr", "mail.by", "mail.mezimages.net", "mail.zp.ua",
  "mail1a.de", "mail21.cc", "mail2rss.org", "mail333.com", "mail4trash.com",
  "mailbidon.com", "mailbiz.biz", "mailblocks.com", "mailbucket.org",
  "mailcat.biz", "mailcatch.com", "maildrop.cc", "maileater.com", "mailexpire.com",
  "mailfa.tk", "mailforspam.com", "mailfreeonline.com", "mailguard.me",
  "mailin8r.com", "mailinater.com", "mailinator.com", "mailinator.net",
  "mailinator.org", "mailinator2.com", "mailincubator.com", "mailismagic.com",
  "mailme.lv", "mailme24.com", "mailmetrash.com", "mailmoat.com",
  "mailms.com", "mailnesia.com", "mailnull.com", "mailorg.org", "mailpick.biz",
  "mailrock.biz", "mailscrap.com", "mailshell.com", "mailsiphon.com",
  "mailtemp.info", "mailtome.de", "mailtothis.com", "mailtrash.net",
  "mailtv.net", "mailtv.tv", "mailzilla.com", "makemetheking.com",
  "manybrain.com", "mbx.cc", "mega.zik.dj", "meinspamschutz.de",
  "meltmail.com", "messagebeamer.de", "mezimages.net", "mierdamail.com",
  "mintemail.com", "moburl.com", "moncourrier.fr.nf", "monemail.fr.nf",
  "monmail.fr.nf", "msrc.ml", "mt2009.com", "mt2014.com", "mt2015.com",
  "mx0.wwwnew.eu", "mycard.net.ua", "mycleaninbox.net", "mymail-in.net",
  "mypacks.net", "mypartyclip.de", "myphantomemail.com", "mysamp.de",
  "mytrashmail.com", "neomailbox.com", "nepwk.com", "nervmich.net",
  "nervtmich.net", "netmails.com", "netmails.net", "neverbox.com",
  "no-spam.ws", "nobulk.com", "noclickemail.com", "nogmailspam.info",
  "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com", "nospam.ze.tc",
  "nospam4.us", "nospamfor.us", "nospammail.net", "notmailinator.com",
  "nowhere.org", "nowmymail.com", "nurfuerspam.de", "nus.edu.sg",
  "objectmail.com", "obobbo.com", "odnorazovoe.ru", "oneoffemail.com",
  "onewaymail.com", "onlatedotcom.info", "online.ms", "oopi.org",
  "opayq.com", "ordinaryamerican.net", "otherinbox.com", "ourklips.com",
  "outlawspam.com", "outloo.com", "outlok.com", "ovpn.to", "owlpic.com",
  "pancakemail.com", "pcusers.otherinbox.com", "pjjkp.com", "plexolan.de",
  "poofy.org", "pookmail.com", "privacy.net", "privatdemail.net",
  "proxymail.eu", "prtnx.com", "punkass.com", "putthisinyourspamdatabase.com",
  "pwrby.com", "quickinbox.com", "rcpt.at", "reallymymail.com",
  "recode.me", "recursor.net", "reliable-mail.com", "rhyta.com",
  "rmqkr.net", "royal.net", "rtrtr.com", "s0ny.net", "safe-mail.net",
  "safersignup.de", "safetymail.info", "safetypost.de", "saynotospams.com",
  "schafmail.de", "schrott-email.de", "secretemail.de", "secure-mail.biz",
  "selfdestructingmail.com", "sendspamhere.com", "sharedmailbox.org",
  "sharklasers.com", "shieldemail.com", "shiftmail.com", "shitmail.me",
  "shitware.nl", "shmeriously.com", "shortmail.net", "sibmail.com",
  "sinnlos-mail.de", "siteposter.net", "skeefmail.com", "slapsfromlastnight.com",
  "slaskpost.se", "smashmail.de", "smellfear.com", "snakemail.com",
  "sneakemail.com", "snkmail.com", "sofimail.com", "sofort-mail.de",
  "sogetthis.com", "soodonims.com", "spam.la", "spam.su", "spam4.me",
  "spamavert.com", "spambob.com", "spambob.net", "spambob.org", "spambog.com",
  "spambog.de", "spambog.ru", "spambox.info", "spambox.us", "spamcero.com",
  "spamcon.org", "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
  "spamcowboy.org", "spamday.com", "spamex.com", "spamfree.eu", "spamfree24.com",
  "spamfree24.de", "spamfree24.eu", "spamfree24.info", "spamfree24.net",
  "spamfree24.org", "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamherelots.com", "spamhereplease.com", "spamhole.com", "spamify.com",
  "spaminator.de", "spamkill.info", "spaml.com", "spaml.de", "spammotel.com",
  "spamoff.de", "spamslicer.com", "spamspot.com", "spamthis.co.uk",
  "spamthisplease.com", "spamtroll.net", "speed.1s.fr", "supergreatmail.com",
  "supermailer.jp", "suremail.info", "tafmail.com", "talkinator.com",
  "tapchicuoihoi.com", "teewars.org", "teleworm.com", "teleworm.us",
  "temp-mail.com", "temp-mail.org", "temp-mail.ru", "tempail.com",
  "tempemail.biz", "tempemail.com", "tempemail.net", "tempinbox.co.uk",
  "tempinbox.com", "tempmail.com", "tempmail.de", "tempmail.eu",
  "tempmail.it", "tempmail.us", "tempmail2.com", "tempmaildemo.com",
  "tempmailer.com", "tempmailer.de", "tempomail.fr", "temporarily.de",
  "temporarioemail.com.br", "temporaryemail.net", "temporaryforwarding.com",
  "temporaryinbox.com", "temporarymailaddress.com", "tempthe.net",
  "thanksnospam.info", "thankyou2010.com", "thc.st", "thelimestones.com",
  "thisisnotmyrealemail.com", "throwam.com", "throwawayemailaddresses.com",
  "throwawaymail.com", "throwaway.email", "tilien.com", "tittbit.in",
  "tmail.ws", "tmailinator.com", "toomail.biz", "topranklist.de",
  "tradermail.info", "trash-amil.com", "trash-mail.at", "trash-mail.com",
  "trash-mail.de", "trash2009.com", "trashdevil.com", "trashemail.de",
  "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.ws", "trashymail.com",
  "tyldd.com", "uggsrock.com", "umail.net", "uplipht.com", "upliftnow.com",
  "venompen.com", "veryrealemail.com", "vidchart.com", "viditag.com",
  "viralplays.com", "vpn.st", "vsimcard.com", "vubby.com", "wasteland.rfc822.org",
  "webemail.me", "webm4il.info", "wegwerfadresse.de", "wegwerfemail.com",
  "wegwerfemail.de", "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net",
  "wegwerfmail.org", "wh4f.org", "whatpaas.com", "whyspam.me",
  "willhackforfood.biz", "willselfdestruct.com", "winemaven.info",
  "wronghead.com", "wuzup.net", "wuzupmail.net", "www.e4ward.com",
  "www.gishpuppy.com", "www.mailinator.com", "wwwnew.eu", "x.ip6.li",
  "xagloo.com", "xemaps.com", "xents.com", "xmaily.com", "xoxy.net",
  "yahho.com", "yaho.com", "yapped.net", "yeah.net", "yep.it", "yogamaven.com",
  "yopmail.com", "yopmail.fr", "yopmail.net", "you-spam.com", "yuurok.com",
  "z1p.biz", "za.com", "zehnminuten.de", "zehnminutenmail.de", "zetmail.com",
  "zippymail.info", "zoaxe.com", "zoemail.org", "zomg.info"
]);

// Typos comuns de provedores grandes → sugestão
export const COMMON_TYPOS: Record<string, string> = {
  // gmail
  "gmial.com": "gmail.com",
  "gmai.com": "gmail.com",
  "gnail.com": "gmail.com",
  "gmal.com": "gmail.com",
  "gmaill.com": "gmail.com",
  "gmali.com": "gmail.com",
  "gemail.com": "gmail.com",
  "gmail.co": "gmail.com",
  "gmail.cm": "gmail.com",
  "gmail.con": "gmail.com",
  "gmail.om": "gmail.com",
  // hotmail
  "hotmial.com": "hotmail.com",
  "hotmai.com": "hotmail.com",
  "hotmali.com": "hotmail.com",
  "hotmsil.com": "hotmail.com",
  "hotmal.com": "hotmail.com",
  "hotmaill.com": "hotmail.com",
  "hotmail.co": "hotmail.com",
  "hotmail.cm": "hotmail.com",
  "hotmail.con": "hotmail.com",
  "hotmail.om": "hotmail.com",
  // outlook
  "outloo.com": "outlook.com",
  "outlok.com": "outlook.com",
  "outlock.com": "outlook.com",
  "outloook.com": "outlook.com",
  "outlook.co": "outlook.com",
  "outlook.cm": "outlook.com",
  "outlook.con": "outlook.com",
  // yahoo
  "yaho.com": "yahoo.com",
  "yahho.com": "yahoo.com",
  "yahooo.com": "yahoo.com",
  "yahoo.co": "yahoo.com",
  "yahoo.cm": "yahoo.com",
  "yahoo.con": "yahoo.com",
  // uol / bol
  "uoll.com.br": "uol.com.br",
  "uol.cm.br": "uol.com.br",
  "uol.com.b": "uol.com.br",
  "boll.com.br": "bol.com.br",
  // icloud
  "iclod.com": "icloud.com",
  "icoud.com": "icloud.com",
  "icloud.co": "icloud.com",
  "icloud.cm": "icloud.com",
};
